### ISSUE TITLE
Coordinate Data Delayed

### ISSUE THREAD

**Issue by tripinva** [bluelinepc/signalcheck#16]
Some of my newer (Android 10 or 11) devices have recently been experiencing an issue where the GPS data appears to come through correctly, but in a delayed fashion such that all my trails (and logs) have GPS coordinates that are some number of minutes delayed relative to the actual location of the device.  This was discussed a bit in both the S4GRU forum, and yesterday I attempted to send diagnostics while it was happening on my Pixel 3a (FreedomPop/AT&T).

I'm not sure what triggers it, though I suspect it's related to the phone being asleep.  That said, I can cure it by completely exiting SCP and reopening, if I notice it happening.  Upon doing so, it will first display the previous coordinates it had displayed prior to exiting, then very rapidly zoom through its apparent queue of coordinates in order to "catch up" to where the device is now.

**Device details**
 - Device: Samsung S21FE
 - Android version: 12
 - SignalCheck version:  4.713b, but started on a previous version

**Comment by TripEricson** [comment]
I've experienced this problem on my Pixel 3a (Android 12, I think), my Revvlry (Android 10), and my Moto One 5G Aces (Android 11).  I do not recall seeing it on my Moto E5 Play devices (Android 8).  

Just bought a Samsung A42 5G which arrived today to use with Verizon.  We'll see what it does.

**Comment by reyvirani** [comment]
I’ve seen this on my Galaxy S10, Galaxy S22 and Galaxy Z Flip3.

**Comment by mikejeep** [comment]
Location Service was overhauled in beta version 4.742b to hopefully alleviate these issues. Please monitor and respond if behavior seems any different.. thanks!

**Comment by mikejeep** [comment]
I was able to duplicate the "racing" location updates with 4.745b.. will continue to explore a resolution.

**Comment by mikejeep** [comment]
Catching up on all of my notes.. is this still an issue for anyone? I have not been able to reproduce recently.

**Comment by TripEricson** [comment]
Being honest, I restart SCP every time I get in the car specifically to avoid this issue, so I can't say one way or another.  On some "safer" trips coming up I'll see if I can reproduce it.

**Comment by mikejeep** [comment]
Checking in, any further issues with this location glitch?

**Comment by TripEricson** [comment]
I've quit restarting SCP every time I get in the car and haven't noticed it happening again.  So I'm not sure there's still an issue here.  Very odd though.

**Comment by mikejeep** [comment]
Wonder if it was an API issue.. who knows. Will close for now, feel free to re-open if you observe this bug again. Thanks!
