### ISSUE TITLE
n41 reported as n7/n38 on Samsung A32 when PLMN is unknown

### ISSUE THREAD

**Issue by mikejeep** [bluelinepc/signalcheck#17]
----- 5G-NR 2600 -----
SS-RSRP: -107 dBm (33 asu)
SS-RSRQ: -11 dB, SS-SINR: 10 dB
PCI: 437
DL NR-ARFCN: 527790 (2638.95 MHz)

7 Neighbor Cells:
369 n7 (-115 dBm)
464 n7 (-118 dBm)
293 n7 (-122 dBm)
169 n7 (-123 dBm)
748 n7 (-125 dBm)
492 n7 (-125 dBm)
422 n7 (-44 dBm)

**Comment by mikejeep** [comment]
~~Fix pending in 4.714~~
Work in progress

**Comment by TomSenpai** [comment]
Also been having the same issue on my Samsung Galaxy s22 Ultra. It shows n38/n7 in areas where n41 and n71 are present. I'm on the T-Mobile network and as far as I know n71 and n41 are the only 5G bands deployed at the moment and n25 currently in testing phase not yet deployed.

**Comment by mikejeep** [comment]
Thanks @TomSenpai . It is an issue with the Samsung firmware that they have not resolved; I have a workaround in testing that will likely be included in the next app update.

**Comment by mikejeep** [comment]
~~Updated fix pending in 4.715~~
Work in progress

**Comment by mikejeep** [comment]
~~Fix pending in 4.716~~
Work in progress.

**Comment by mikejeep** [comment]
This is an Android bug; if users could add a "+1" on it, this will help attract attention for it to be properly fixed at the OS level: https://issuetracker.google.com/issues/253539094

**Comment by TomSenpai** [comment]
It seems like this bug might have been fixed. Signal Check Pro is now showing the right band (N41) when connected to NR - 2500 MHz.


![Screenshot_20221121_171757_SignalCheck Pro](https://user-images.githubusercontent.com/110506130/203169656-2bd29bca-01c0-4598-a883-2d94fd816351.jpg)

**Comment by mikejeep** [comment]
Resolved in version 4.73, released today.
