### ISSUE TITLE
Add Option for Automatic Connection Reset When Service Drops

### ISSUE THREAD

**Issue by TripEricson** [bluelinepc/signalcheck#20]
I have two phones that don't handle changes in TAC very well.  They log fine right until the TAC changes, then they drop to no service and it takes several minutes for them to try again, unless I manually intervene and use the "Reset Connection" button.  (Both are rooted, so that works for them.)

I wish SCP had an option I could enable on those devices where I could have it automatically reset the connection when the connection drops.  And if it doesn't come back (because I'm actually in a no signal area), perhaps have a setting where it could reset the connection every however often (maybe the duration could be customized?) until a connection returns.  

The alternative would be to buy new devices, or do as I'm doing, keep the phone in sight and hit the button while I'm barreling down the highway.  I'd really rather have the phone do it automatically; it'd be both cheaper and safer.

**Comment by TripEricson** [comment]
Having watched one of my phones yesterday while driving, I think the behavior would be something like:

- Resets 2 seconds after connection drops from "Connected to LTE" or "Restricted LTE" to "Connecting.." or "No mobile connection."  Then the time delay duration kicks in only for subsequent failures to connect.
- Does not reset if screen is off/locked or airplane mode was manually engaged. (If you can tell that.)

I feel like there was more that I'd thought of, but I'm not thinking of it.  I'll be out and about again today with it.

**Comment by mikejeep** [comment]
Beta release 4.744b coming soon will include a new option, _Preferences > General Settings > Automatic Connection Reset_. If this option *AND* the "No Mobile Signal" alert are both enabled, the connection should reset upon mobile connection loss. If this proves to be reliable, I can work on eliminating the need to have the "No Mobile Signal" alert enabled.

**Comment by mikejeep** [comment]
Checking in on this very old request -- did it do the trick?

**Comment by TripEricson** [comment]
I feel a bit sheepish, but the phones I needed this for have been rotated out.  Unless someone else can use it, I am fine with you just closing this one and/or removing it from the software.
