### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Nextelplussprintone** [bluelinepc/signalcheck#21]
The old sprinttowers still showing as sprint not tmobilel ocally**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Device details**
 - Device: 
 - Android version: 
 - SignalCheck version: 

**Additional context**
Please add any other context about the problem here.

**Comment by Nextelplussprintone** [comment]
![image](https://user-images.githubusercontent.com/113238487/189479002-4f107fdc-2e87-4d10-aae4-8eb491c3995b.png)

**Comment by Nextelplussprintone** [comment]
Unless I'm incorrect about the problem hopefully you can help me understand. 
Thanks have a great day!!

**Comment by TomSenpai** [comment]
> Unless I'm incorrect about the problem hopefully you can help me understand. Thanks have a great day!!

I'm not 100% sure but I believe B25, B26, and B41 will continue to register as Sprint sites until T-Mobile converts those sites. Most of the B25, 26, 41 sites that remain are Sprint Keep sites but T-Mobile is supposed to move B25 over to 5G (n25), sell most, if not all of B26 to Dish, and continue to convert B41 over to its Ultra Capacity 5G (n41).

**Comment by Nextelplussprintone** [comment]
Thanks sir for your response I figured so but was trying to understand this. Have a great day.

**Comment by Nextelplussprintone** [comment]
Thanks for your response.  Another question been a while since an app
update any in the works was just a thought and yes I contribute to this app
when possible still. It's well worth it and the best out there.

**Comment by TomSenpai** [comment]
> Thanks for your response. Another question been a while since an app update any in the works was just a thought and yes I contribute to this app when possible still. It's well worth it and the best out there.
> […](#)

I have no idea when there will be a new app update... just like you, I contribute/donate to the app whenever possible. I think @mikejeep may know more about the next app update since there were talks of bug fixes in a new update he described as  4.714  that he says is in testing.

**Comment by mikejeep** [comment]
As mentioned above, this is not a bug; some sites/devices are still configured as Sprint. As T-Mobile updates its network, sites change and will be automatically be reflected in the app.
