### ISSUE TITLE
5G NR 600 showing NR 2500 frequency and vice versa

### ISSUE THREAD

**Issue by shoman94** [bluelinepc/signalcheck#24]
If connected to NR600 first it will never display NR2500 even when changing frequency.  The opposite happens if connected to NR2500 first.

This is on a Pixel 7 on Android 13. I have sent diags within the app

**Comment by mikejeep** [comment]
Fix pending in 4.716

**Comment by shoman94** [comment]
Thanks

**Comment by mikejeep** [comment]
Resolved in version 4.73, released today.
