### ISSUE TITLE
When connected to a WiFi 6 network it still shows (AC)

### ISSUE THREAD

**Issue by shoman94** [bluelinepc/signalcheck#25]
**Describe the bug**
Wifi 6 displays (ac)

**To Reproduce**
Connect to WiFi 6

**Expected behavior**
Should display (ax)

**Screenshots**

**Device details**
 - Device: Galaxy s21, Galaxy s20, Pixel 6, Pixel 7
 - Android version: Android 12 and Android 13
 - SignalCheck version: latest

**Additional context**
Please add any other context about the problem here.

**Comment by mikejeep** [comment]
Wi-Fi 6 support is currently in testing, will be included in release 4.716b and public release coming soon.

**Comment by shoman94** [comment]
Thank you, any way I can become a tester?

**Comment by mikejeep** [comment]
> Thank you, any way I can become a tester?

Sorry for missing this post. Please send an e-mail to support@signalcheck.app.

**Comment by mikejeep** [comment]
Resolved in version 4.73, released today.
