### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by shoman94** [bluelinepc/signalcheck#28]
**Is your feature request related to a problem? Please describe.**
Ability to use the app within Android Auto.

**Describe the solution you'd like**
Support added 😂

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mikejeep** [comment]
I understand this would be useful (I would enjoy it myself), however Android Auto only permits specific categories of apps -- media, messaging, navigation, or custom vehicle-specific apps (i.e. apps that enhance functionality of electric vehicles). SignalCheck does not fit into any of these categories, so it would be a violation of the Android Auto guidelines and likely rejected and removed from the Play Store.

My assumption is that permitting development of other apps would serve as a driving distraction, which isn't unreasonable.
