### ISSUE TITLE
App stuck in reading data from the wrong SIM slot

### ISSUE THREAD

**Issue by jackyyf** [bluelinepc/signalcheck#44]
**Describe the bug**
SignalCheck Pro is stuck reading data from incorrect SIM slot (SIM1), and only SIM0 has sim card inserted.

**To Reproduce**
I do not have a stable reproduce of this issue, nor do I know how to switch between 2 SIM slots :P

**Expected behavior**
As only 1 SIM card is inserted, app should use that slot.

**Device details**
 - Device: Xiaomi 11 Lite 5G NE
 - Android version: 13 TKQ1.220829.002 (MIUI by xiaomi.eu 14)
 - SignalCheck version: 4.78
 - Device is rooted with Magisk

**Additional context**
It was on the correct sim until earlier this day, and I've tried to disable the incorrect sim, remove the sim from the incorrect slot (without and with reboot after both actions).
Tried clear data on the app with force stop, still no luck. 

Please let me know if any other methods I could try, and I would be happy to help on debugging :)

**Comment by mikejeep** [comment]
Sorry for delay in responding to this. I found your diagnostic report, and believe this may be a Xiaomi issue. The OS was reporting no cell information at the time of your report. The app pulls from whatever the OS determines is the primary SIM/connection at the time. Dual-SIM support is in the final stages of testing, but not ready for public release yet. Have you tried updating to the latest version of SignalCheck (4.81)?

**Comment by mikejeep** [comment]
Closing due to no response, please feel free to re-open and reply if you have further information.
