### ISSUE TITLE
Add Support for Data from Unactivated SIM

### ISSUE THREAD

**Issue by TripEricson** [bluelinepc/signalcheck#47]
EDIT:  Actually, now I'm realizing there is a "Show Hidden Data" checkbox in the Display tab which is already checked.  So maybe this is a bug and not an enhancement?

Yesterday, I got a Rainbow SIM from Boost Mobile, and while it's not yet activated, it looks like the phone is actually reporting data out via the API.  Unfortunately, it appears that SignalCheck is not actually making use of that data.

I'm sitting at my desk at work, and I've attached two photos.  One is what SCP is showing me on the main screen, and the other is what SCP has in the diagnostics screen.  The diagnostics screen clearly shows the data the phone is seeing, but SCP doesn't report it.

![Screenshot_20231024-084918](https://github.com/bluelinepc/signalcheck/assets/43734293/ba5db9b1-421f-4ffe-9660-4225c677e4aa)
![Screenshot_20231024-084902](https://github.com/bluelinepc/signalcheck/assets/43734293/587393c3-2b6c-4c95-b9ab-4ddc2f7fa346)

I can certainly imagine that in the typical case, data like this could be untrustworthy, but it would be nice if I could check a box in the General preference menu, perhaps, and enable SCP to show and log this data.  It'd be a heck of a lot cheaper than actually signing up for Boost Mobile service, I'll say that.

**Comment by mikejeep** [comment]
I should be able to get this working, as I use an inactive SIM myself without any special settings. Is the data on the screen not in sync with what is showing on the diagnostic screen? I see the signal strength does not match but most of the other looks like it's there, except for PLMN and NCI. Did you happen to try toggling the option under **Preferences > General Settings > Use Alternate PLMN ID**? Please send a diagnostic report when connected if you can!

**Comment by TripEricson** [comment]
The RSRP, RSRQ, and SINR appear to be incorrect, and the PLMN and NCI are missing.  I'll try that option when I'm back at my desk (sitting in a meeting right now).  I'll also try to send some diagnostics when I do so; I know I prepared some earlier but, of course, I have no connection right now.  I'll have to tether.

**Comment by TripEricson** [comment]
Update:  Alternate PLMN ID did not work.  In fact, now, regardless of that setting, I'm not getting anything on the main screen, just "No Connection."  The diagnostic screen still shows valid cell info.

I sent you my saved diagnostics from earlier, and also a new set from just now.

EDIT:  Just got home (went out to dinner before coming home).  Sent another set of diagnostics once I got home, and did eventually see the main screen data appear again.  It looks like it just doesn't update very frequently.  Meanwhile, what is shown on the diagnostic screen updates as frequently as a phone normally would.

**Comment by mikejeep** [comment]
I think I have figured out what is going on here _(EDIT: thanks to your diagnostic report)_.. the app is interpreting it as a 5G-NR neighbor cell -- which causes it to be completely hidden when there is no primary connected cell. I'm on it.

**Comment by mikejeep** [comment]
Fix pending in 4.824b.

**Comment by mikejeep** [comment]
Any feedback yet @TripEricson ?

**Comment by TripEricson** [comment]
I've not stuck my unactivated Rainbow SIM in a phone yet to test that specific case, but I definitely had some US Cellular appear on my n41 phone when outside of T-Mobile n41 SA range.  Last time I did that, that didn't happen, even though Cell Mapper recorded some data.  I'll have to check the log and see if it recorded, but I assume if it displays it will record.

In short, it does seem better!  I'll have to do more testing though.

**Comment by mikejeep** [comment]
Any more observations on this bug?

**Comment by TripEricson** [comment]
Ack, I keep forgetting about this one.  I need to park my unactivated SIM in a device to test, and haven't done that yet.  I'll try to find time to do this soon.

**Comment by TripEricson** [comment]
Just put my unactivated Dish Rainbow SIM in one of my Samsung A42 5G phones.  Data shows in Cell Mapper, but not in SCP.  Just sent diagnostics.  

I'm probably going to remove this SIM and activate another Tello SIM at the end of the week, so if you want me to do anything else with it, the next few days are probably best.

**Comment by mikejeep** [comment]
> Just put my unactivated Dish Rainbow SIM in one of my Samsung A42 5G phones. Data shows in Cell Mapper, but not in SCP. Just sent diagnostics.

Did you have WiFi or another connection when you sent it? I'm not seeing anything received. If you connect that device, the original report is saved, if you go to the diagnostics option under Help you can send it (or it will be sent if you send another report).

**Comment by TripEricson** [comment]
Whoops.  You should have it now.

**Comment by mikejeep** [comment]
Fix pending in 4.832b rolling out now, let me know!

**Comment by mikejeep** [comment]
Checking in, any further observations of this bug?

**Comment by TripEricson** [comment]
I can't find my spare Rainbow SIM, but I had a spare expired (2020!) T-Mobile SIM and I am, in fact, seeing data on my A52.  I'm willing to say you can close this one, unless you want to wait for me to find my Rainbow SIM (if I do).
