### ISSUE TITLE
Coordinates as a "Here" note option

### ISSUE THREAD

**Issue by RyanThaDude** [bluelinepc/signalcheck#51]
When mapping I find myself using the "Here" button in notes quite a bit when I find a new site, but it doesn't always give me proper address, especially when on an interstate or an area that doesn't have any valid addresses. I process my data at home on my PC and those invalid addresses can sometimes make it difficult to figure out where I found it.

A suggestion is to add an option, in settings, that we can change that allows either address or coordinates. When I return home, just looking up the coordinates in maps would be so much easier and faster to get a proper location. Thanks!

**Comment by mikejeep** [comment]
Thank you for the suggestion! An option for this will be added to the next release under _Preferences > Display Settings > Site Notes > Geocode Location Address_. By default, it will be enabled (matching current behavior, geocoding the street address); to populate the coordinates instead, you would want to uncheck this box.

The next release date is TBD but will hopefully soon. If you experience any problems with this feature after updating, please feel free to re-open this issue.
