### ISSUE TITLE
The persistent notification should show the NR SA band

### ISSUE THREAD

**Issue by eladts** [bluelinepc/signalcheck#54]
**Is your feature request related to a problem? Please describe.**
The persistent notification does not show the NR SA band even if it is known and shown in the UI and in the notification icon.

**Describe the solution you'd like**
The band should be shown, like it is for LTE and NRA NSA, for example, in the screenshot below the notification should show `5G-NR (T-Mobile n41)` in its title.

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot_20240117-214205](https://github.com/bluelinepc/signalcheck/assets/6475871/a13b525b-d808-415a-9368-94af26461698)

**Comment by mikejeep** [comment]
Thank you for your suggestion! This improvement is now in testing and will be available in the next release.
