### ISSUE TITLE
Show CA bandwidth and UL frequency

### ISSUE THREAD

**Issue by eladts** [bluelinepc/signalcheck#55]
**Is your feature request related to a problem? Please describe.**
SignalCheck Pro only shows carrier aggregation bandwidth data for LTE or LTE + NR NSA. This information isn't shown at all for NR SA, even though other apps such as CellMapper are showing it. Also, the upload frequency and NR-ARFCN are never shown even in FDD bands such as n25 and n71.

**Describe the solution you'd like**
Show the CA bandwidth data and UL frequency for NR SA when available. Rename the option _Show LTE Carrier Aggregation_ to _Show LTE/NR Carrier Aggregation_.

**Describe alternatives you've considered**
N/A

**Additional context**
A screenshot from CellMapper showing NR SA CA bandwidth data and UL frequency.
![image](https://github.com/bluelinepc/signalcheck/assets/6475871/d26cc659-4088-405f-a336-077ada984065)

**Comment by mikejeep** [comment]
Unfortunately, the current Android API does not provide any method to obtain 5G-NR carrier aggregation or bandwidth information, or upload ARFCN identification. Any other apps that display the information are likely using proprietary methods that I am not privy to. If you have a method to do so, please feel free to re-open this ticket with details. A ticket was already filed on the Android Issue Tracker related to this, please upvote it here to encourage development of these features: https://issuetracker.google.com/issues/198678685

**Comment by TomSenpai** [comment]
I'm wondering if the Cell Mapper app that's shown in the previous screenshot above is pulling the 5G-NR carrier aggregation bandwidth information from the service mode screen. Service mode pulling the SIM information is able to display 5G-NR carrier aggregation and bandwidth along with the band numbers.

![Image](https://github.com/user-attachments/assets/ad7b03fb-1fa5-48e9-bcbf-544184ea3209)
