### ISSUE TITLE
Add Option to Prevent LTE Data from Jumping When Using 5G-NR NSA

### ISSUE THREAD

**Issue by TripEricson** [bluelinepc/signalcheck#61]
I don't use my phone without band locking often, but I've done it a bit recently and one thing that drives me nuts is that when I'm connected to LTE but it's using 5G-NR NSA, because NSA is only reported when it's in use, the 5G-NR section of the display appears and disappears frequently, pushing the other items on the screen down and up again repeatedly.  It can jump very rapidly, sometimes more than once per second, making it very challenging to read the LTE section of the display.

I've come up with two possible solutions to this issue:

1) An option (disabled by default) could be added to basically hold that space open when the 5G-NR data disappears just so the LTE data won't jump around so much.  Basically, when it drops NSA, it would look like this:

![Screenshot_20240313-192345_SignalCheck Pro](https://github.com/bluelinepc/signalcheck/assets/43734293/e81abaf7-81cc-4816-a363-92398c1d9934)

2) Alternatively, maybe the option could move the 5G-NR NSA data to below the LTE section, and perhaps add "(5G-NSA)" to the "LTE 1900" (for example) row between that text and the signal strength bar.  Considering it lacks identifying information anyway, just signal level information, putting it at the bottom wouldn't really hurt anything.

**Comment by mikejeep** [comment]
New option added to display LTE info above NR info; it is disabled by default, but can be enabled by going to **Preferences > Display > Show LTE Cells Above 5G-NR Cells**. It is included in beta version 4.843b, which is rolling out now.. let me know how it looks and if it solves your concern!

**Comment by TripEricson** [comment]
I love it!  Looks great.  Thanks so much!
